Smartbanner for dynamic web app (vuejs)
ain/smartbanner.js pull request #589
Opened 2023-01-27 17:47 UTC by Beauceron

2023-01-28 12:14 UTC, ain requested changes
Thanks for the great contribution @Beauceron!

With Code Review completed, I'd call you to also add the specs in areas affected. 

I added Coveralls support in [aee68f5](https://github.com/ain/smartbanner.js/commit/aee68f5dac61959d8864351aaba68b988625dacf) now so you'd be able to get a report on your next commit and an overview on your changes at https://coveralls.io/github/ain/smartbanner.js

Let me know if you have any questions/issues!

2023-02-22 23:08 UTC, Beauceron commented
@ain I also have the eslint failing because of this rule : 
```
    "linebreak-style": [
      "error",
      "unix"
    ],
```
I have all the JS files in CRLF on local but eslint recommand LF. 

Is this my IDE that make that or you have the same thing?

2023-02-23 02:36 UTC, Beauceron commented on src/smartbanner.js
> +    body.classList.add(OPEN_BODY_CLASS);
@ain I added some test please take a look.

2023-03-28 21:10 UTC, ain commented
@Beauceron no, I don't have that problem as Vim is Unix-compatible by default.

In most IDEs you are able to save files in Unix format as opposed to Windows.

The reasoning of the LF requirement is that the code is mostly run on the Unix-compatible platforms, e.g. Linux.

Could you please merge the latest `main` branch into your PR and retry linting?

2023-06-09 08:25 UTC, ain commented
We had to withdraw the change in `main` as per the errors seen, other solutions need to be found for `eslint` failures.

2023-07-16 02:55 UTC, closed without merging